### ISSUE TITLE
Does not work in Mendix 11.5

### ISSUE THREAD

**Issue by lukastom** [ArjenLammers/csv-connector#21]
The error is `cannot find symbol Long start = ((long) Core.getMetaObject(entity).getId()) << 48;`

**Comment by ArjenLammers** [comment]
Fixed in just released version in Marketplace.
